### ISSUE TITLE
Bad

### ISSUE THREAD

**Issue by rocketengineer** [tjsnell/camel-aws#2]
It does NOT work. Did you spend too much time writing crap on IRC when authoring this pile of crap?

**Comment by massfords** [comment]
Obviously some kind of flame war going on here but it's probably a good opportunity to remove this project entirely from GitHub since it was merged into Camel years ago.

**Comment by tjsnell** [comment]
True. Was my first Camel component and one that has become crazy popular. Kept it for historical reasons. I'll remove it.
